### PR TITLE
3 fixes at once

### PR DESCRIPTION
**Pull request by plokhotnyuk**
- OOM for `sbt clean +compile`
- test failures for `sbt clean +test` after https://github.com/sirthias/borer/commit/895455f2b61743b4e7844547864b6f612fae9f13
- compilation error for `sbt -java-home /usr/lib/jvm/openjdk-11 clean +test` that should close https://github.com/sirthias/borer/issues/45

### CODE REVIEW

**Comment by plokhotnyuk** [comment]
A good follow up would be adding of Travis CI or/and AppVeyor integration.

It will open a way for checked pull requests from contributors or @scala-steward (see the https://github.com/fthomas/scala-steward repo)

**Comment by sirthias** [comment]
Thank you, @plokhotnyuk !
